#-mode python-
Import('env')
env = env.Clone()

cpps = Glob('*.cpp')
test_cpps = [str(fn) for fn in Glob('*.cpp')]
test_sources = [
    '#test/dotest.cpp',
    test_cpps,
]

env.Append(LIBS=['cppunit'])
env.Append(LIBS=['maxentropy'])
env.Append(LIBS=['classifier'])
env.Append(LIBS=['AliWS'])
env.Append(LIBS=['word_seg'])
env.Append(LIBS=['protobuf'])
env.Append(LIBS=['pthread'])
env.Append(LIBS=['crfpp'])
env.Append(LIBS=['crf_model'])
env.Append(LIBS=['dict_matcher'])
env.Append(LIBS=['post_processer'])
env.Append(LIBS=['pattern'])
env.Append(LIBS=['pcre'])
env.Append(LIBS=['nlu_reg'])
env.Append(LIBS=['tiny'])
env.Append(LIBS=['nlu_processer'])
env.Append(LIBS=['alog'])
env.Append(LIBS=['autil'])
env.Append(LIBS=['config++'])
env.Append(LIBS=['rt'])
env.Append(LIBS=['dl'])

env.aTest(target = 'nlu_processer_test',
          source = test_sources,
)
