#-mode python-
Import('env')
env = env.Clone()

crf_model = Glob('*.cc')
crf_model_cpps = [crf_model]
env['LIBS'] = ['AliWS', 'proto_def']

env.aLibraryAndInstall(target = 'crf_model',
                       source = crf_model_cpps,
                       LIBS = env['LIBS'],
                      )

env.aDirs('crf_model_test')
Return(['crf_model_cpps'])
