#-mode python-
Import('env')
env = env.Clone()

classifier = Glob('*.cc')
classifierccs = [classifier]
env['LIBS'] = ['proto_def']

env.aLibraryAndInstall(target = 'classifier',
                       source = classifierccs,
    LIBS = env['LIBS'],
                      )

env.aDirs('classifier_test')

Return(['classifierccs'])
