# -*- mode: python -*-
import os, sys
# Inherit the environment from my parent.
Import('env')

# Make a copy of the environment, so my changes are limited in this directory and sub-directories.
env = env.Clone()

cpps = Glob('*.cc')

env['LIBS'] = [
               'dl',
               'alog',
               'autil',
               'proto_def',
               'word_seg',
               'libconfig++',
               'maxentropy',
               'AliWS',
               'protobuf',
               'pthread',
               'crfpp',
               'crf_model',
               'classifier',
               'dict_matcher',
               'post_processer',
               #'nlu_processer',
               'pattern',
               'pcre',
               'nlu_reg',
               'tiny',
              ]

env.aProgramAndInstall(
    target = 'case_test',
    source = cpps,
    LIBS = env['LIBS'],
    dirInPackage = 'bin'
)

