#-mode python-
Import('env')
env = env.Clone()

cpps = Glob('*.cpp')
test_cpps = [str(fn) for fn in Glob('*.cpp')]
test_sources = [
    '#test/dotest.cpp',
    test_cpps,
]

env.Append(LIBS=['cppunit'])
env.Append(LIBS=['maxentropy'])
env.Append(LIBS=['classifier'])
env.Append(LIBS=['alog'])
env.Append(LIBS=['autil'])
env.Append(LIBS=['config++'])
env.Append(LIBS=['rt'])
env.Append(LIBS=['dl'])

env.aTest(target = 'classifier_test',
          source = test_sources,
)
