#-mode python-
Import('env')
env = env.Clone()

src_proto = ["classifier.pb.cc",
             "qp.pb.cc",
             "nlu_dm.pb.cc"]

env['LIBS'] = ['protobuf']

env.aLibraryAndInstall(target = 'proto_def',
                       source = src_proto ,
		                   LIBS = env['LIBS'],
                      )
