#-mode python-
Import('env')
env = env.Clone()

wordseg = Glob('*.cc')
wordsegcpps = [wordseg]
env['LIBS'] = ['AliWS', 'proto_def']

env.aLibraryAndInstall(target = 'word_seg',
                       source = wordsegcpps,
    LIBS = env['LIBS'],
                      )

Return(['wordsegcpps'])
