#-mode python-
Import('env')
env = env.Clone()

nluprocpps = Glob('*.cc')
src_nlupro = [nluprocpps]

#env['LIBS'] = ['AliWS', 'proto_def']

env.aLibraryAndInstall(target = 'nlu_processer',
                       source = src_nlupro,
                      )
env.aDirs('nlu_processer_test')
Return(['src_nlupro'])
