#-mode python-
Import('env')
env = env.Clone()

patterncpps = Glob('*.cc')
src_pattern = [patterncpps]

#env['LIBS'] = ['AliWS', 'proto_def']

env.aLibraryAndInstall(target = 'pattern',
                       source = src_pattern,
                      )
env.aDirs('pattern_test')
env.aDirs('case_test')
Return(['src_pattern'])
